---
- name: ======TEST PLAYBOOK======
  hosts: DynasafeVM
  tasks:
    - name: TEST CONNECTION
      ansible.builtin.ping:
      register: message
    - name: PRINT DEBUG MESSAGE
      ansible.builtin.debug:
        msg: "AAAAAA"
    - name: PRINT VARIABLES
      ansible.builtin.debug:
        msg: "{{ TEST_ECHO_MSG }}{{ TEST_HOST_VARIABLES }}"
  roles:
    - {role: ping-sample, become: true}
