---
 - name: "======INSTALL DOCKER======"
   become: true
   yum:
    name: "{{ item }}"
    update_cache: true
    state: present
   with_items: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin