---
 - name: "======CHECK IF PIP IS INSTALLED OR NOT================"
   become: true
   command: pip --version
   ignore_errors: true
   changed_when: false
   register: pip_is_installed

 - name: "======INSTALL PYTHON3 PIP3======"
   become: true
   yum:
      name: python3-pip
      state: present
      update_cache: yes
   when: pip_is_installed.rc != 0