---
- hosts: DynasafeRockyLinux
  tasks:
    - name: ======TEST CONNECTION======
      ping:
      register: message
    - name: ======PRINT DEBUG MESSAGE======
      debug:
        msg: "AAAAAA"
  roles:
    - role: '../roles/docker-installer'
